### ISSUE TITLE
Provide generator for paths (this would be in addition to the existing `url`)

### ISSUE THREAD

**Issue by richardson-trevor** [travi/any#197]
Many times this wouldn't behaviorally change much for tests, but specifically for semantics it would often be nice to do something like `any.rel()` that would output something like `/blah/ti/dah`

**Comment by travi** [comment]
is this specific to link rels, or more generic for any url that is just the path rather than including the host?

**Comment by richardson-trevor** [comment]
Correct, I just mean a path that does not include a host.

**Comment by travi** [comment]
do you find a need for this. i've been thinking about this since you filed it and havent found it to be a problem in my normal. most of my usage could actually just be `any.string()` because my tests dont find the actual value to be significant. i really only use `any.url()` instead of `any.string()` in order to make it more clear in the test that the value can be assumed to be a valid link.

did you have a use case in mind where the presence of the host was significant?

**Comment by richardson-trevor** [comment]
It was more in regard to clarity like you’re mentioning with url vs string.
That seems totally fair, though. I’d say unless there are stronger
motivations than this, url will be fine.

**Comment by travi** [comment]
ok. im going to close this for now then. we can always reopen if we see enough value in it later
