### ISSUE TITLE
Support for < 0 for any.integer

### ISSUE THREAD

**Issue by richardson-trevor** [travi/any#201]
It would be good to be able to do something like: `any.integer({min:-25, max: 25})`. It looks like the usage under the hood here is chance.natural, which (natural numbers) do not include negatives. With this api being integer, support for all integer values would be good.

**Comment by travi** [comment]
thats certainly fair. i've just never run into a case in my tests where negative integers would be useful, so i captured my common use-case by using natural instead.

i think i would want to maintain the default behavior of using non-negative values, but switching to `chance.integer()` and setting a default `min` of `0` (or `1` might actually be better) would probably enable both. 

interested in sending a PR?

**Comment by richardson-trevor** [comment]
I sure can. Might be a few days.

**Comment by travi** [comment]
since this is now implemented using `integer` from `chance` (was it not when we opened this?) it accepts any options available to `integer`. i think i still like defaulting to a [min of 1](https://github.com/travi/any/blob/cbad4641451655df3b961dfc529aa723ab96f0f3/src/base.js#L36), but it is simple to override the min with a lower value.
